import {Partenaires} from './partenaires';

export const PARTENAIRES: Array<Partenaires> = [
    {
        categorie: "Les croquettes",
        description: "Chez Ultra Premium Direct, nous plaçons la santé de vos chiens et de vos chats au cœur de notre démarche. Nous sommes convaincus que l’alimentation a un impact fondamental sur leur bien-être. C’est pourquoi nous proposons des recettes adaptées au régime naturel carnivore de vos chiens et de vos chats : une alimentation fabriquée sans céréales, ou à faible teneur en céréales.", 
        brand: "Ultra Premium",
        isBio: false,
        isFreeCereal: true,
        isForKitten: true,
        isForAdult: true,
        isForSenior: true,
        isForSterilized: true,
        isForIndoor: true,
        webSite: "https://www.ultrapremiumdirect.com",
    },
    {
        categorie: "Les croquettes",
        description: "Comme de nombreux propriétaires de félins, vous recherchez l’alimentation la plus adaptée pour votre chat. Vous remplissez sa gamelle avec des croquettes de viande fraîche ? Vous lui proposez des pâtées ? Les croquettes pour chat contiennent tous les nutriments essentiels à son bien-être. Elles représentent une solution simple et économique qui se conserve longtemps. ", 
        brand: "Equilibre & instinct",
        isBio: true,
        isFreeCereal: false,
        isForKitten: true,
        isForAdult: true,
        isForSenior: true,
        isForSterilized: true,
        isForIndoor: true,
        webSite: "https://www.equilibre-et-instinct.com/",
    },
    {
        categorie: "Les pâtées",
        description: "La pâtée pour chat Equilibre et instinct est l’une, si ce n’est l’alimentation la plus adaptée pour votre chat, quel que soit son âge. Pour lui assurer une forme et une santé de fer, vous pouvez compter sur ce produit. C’est un aliment préparé artisanalement, donc qui n’intègre que des ingrédients naturels. ", 
        brand: "Equilibre & instinct",
        isBio: true,
        isFreeCereal: false,
        isForKitten: true,
        isForAdult: true,
        isForSenior: true,
        isForSterilized: false,
        isForIndoor: false,
        webSite: "https://www.equilibre-et-instinct.com/",
    }, 
    {
        categorie: "Les friandises",
        description: "Les personnes soucieuses du bien-être de leurs animaux ont à cœur de donner une alimentation de qualité à leur petit compagnon. Les aliments Cosma devraient leur plaire ! Composés à 100 % d‘ingrédients naturels, garantis sans colorants, parfums, substances appétentes, conservateurs artificiels, arômes ni exhausteurs de goût, les produits Cosma font le bonheur des chats, mais aussi celui de leurs maîtres.", 
        brand: "Cosma",
        isBio: false,
        isFreeCereal: false,
        isForKitten: true,
        isForAdult: true,
        isForSenior: true,
        isForSterilized: true,
        isForIndoor: true,
        webSite: "https://www.cosma-catfood.com/fr/",
    }, 
    {
        categorie: "Les friandises",
        description: "Les recettes des croquettes Purizon pour chien et chat ont été inspirées par la Nature. Elles contiennent exclusivement des ingrédients naturels de grande qualité et sont exemptes de céréales.", 
        brand: "Purizon",
        isBio: false,
        isFreeCereal: true,
        isForKitten: true,
        isForAdult: true,
        isForSenior: true,
        isForSterilized: true,
        isForIndoor: true,
        webSite: "https://www.purizon-petfood.de/fr/",
    }, 
]
